name: Set vim

on: 
  push:

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.7.0

      - name : Check neovim
        run : |
          nvim --version

      - name: Install vim-plug
        run : |
          sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
          mkdir -p ~/.config/nvim

      - name : Check vim-plug config file
        run : |
          ls ~/.local/share/nvim/site/autoload

      - name : Create nvim configure file
        run : |
          cat >> ~/.config/nvim/init.vim<<EOF
          call plug#begin('~/.config/nvim/plugged')
          Plug 'neoclide/coc.nvim', {'branch': 'release'}
          call plug#end()
          EOF

      - name: Install vim plug extension
        run : |
          nvim -u ~/.config/nvim/init.vim -V1 -es -c ':PlugInstall' -c ':q!'

      - name : Install coc-tsserver
        run : |
          nvim -u ~/.config/nvim/init.vim -V1 -es -c ':CocInstall -sync coc-tsserver'

      - name: check extension
        run : |
          ls ~/.config/nvim/
          ls ~/.config/nvim/plugged

      - run : ls -al
